Jjdzr2 cl 19 formularz rejestracji nowego wolontariusza
infoshareacademy/jjdzr2-CwaneLisy pull request #27
Opened 2021-01-20 22:36 UTC by MojoJojo-san

2021-01-21 23:29 UTC, ZytaWisz requested changes
Wszystko jest ok, oprocz tych malutkich 3 rzeczy do poprawy :)

2021-01-21 23:29 UTC, ZytaWisz commented on webApp/src/main/java/com/infoshare/controller/VolunteerController.java
> +import javax.validation.Valid;
Nieuzywany import - do usuniecia.

2021-01-21 23:29 UTC, ZytaWisz commented on webApp/src/main/java/com/infoshare/formobjects/VolunteerForm.java
> +    public void setTypeOfHelp() {
Ten setter jest nieuzywany - mozna by go usunac.

2021-01-21 23:29 UTC, ZytaWisz commented on webApp/src/main/java/com/infoshare/controller/VolunteerController.java
> +            return "redicted:/volunteer/all";
Tutaj jest literowka w wyrazie, powino byc: 
```suggestion
            return "redirect:/volunteer/all";
```

2021-01-22 21:34 UTC, MojoJojo-san commented on webApp/src/main/java/com/infoshare/controller/VolunteerController.java
> +            return "redicted:/volunteer/all";
poprawione

2021-01-22 21:34 UTC, MojoJojo-san commented on webApp/src/main/java/com/infoshare/formobjects/VolunteerForm.java
> +    public void setTypeOfHelp() {
setter usuniety

2021-01-22 21:36 UTC, MojoJojo-san commented on webApp/src/main/java/com/infoshare/controller/VolunteerController.java
> +import javax.validation.Valid;
poprawione

2021-01-23 09:57 UTC, ZytaWisz approved these changes

2021-01-23 16:55 UTC, magkamon approved these changes

2021-01-23 16:57 UTC, merged