Wyszukiwanie_wolontariuszy
infoshareacademy/jjdzr2-CwaneLisy pull request #29
Opened 2021-02-02 21:22 UTC by Szymek7

2021-02-03 16:24 UTC, magkamon approved these changes

2021-02-03 16:24 UTC, magkamon commented on webApp/src/main/java/com/infoshare/controller/VolunteerController.java
>      public String searchForVolunteer(Model model) {
może: searchForAvailableVolunteers ? -> początkowo jak testowałam to zapomniałam że to jest kryterium i zastanwaiłam się dlaczego 'nie działa'  ;)

2021-02-03 17:59 UTC, ZytaWisz requested changes

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +<link rel="stylesheet" id="bootstrap-css">
Zły link, nie zaciąga bootstrapa

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +    <title>Volunteer Search Form</title>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +                    <div class="card-header">Look for free Volunteer</div>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +                                <label for="city"  class="cols-sm-2 control-label">City:</label>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +                                               placeholder="Enter city" required="true"/>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +                            <label>Which type of help are you looking for?</label>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-form.html
> +                                <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Search!
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-results.html
> +    <title>ToDoList</title>
Zły tytuł ;)

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-results.html
> +        <h3 class="text-center">All available Volunteers:</h3>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-results.html
> +        <span th:if="${volunteers.size() == 0}">There isn't any available Volunteers right now, check later.</span>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka. Ps powinno być aren't zamiast isn't

2021-02-03 17:59 UTC, ZytaWisz commented on webApp/src/main/resources/templates/volunteer-search-results.html
> +            <th scope="col">Type of Help</th>
skorzystaj  z message properties do przechowywania tekstów dla odpowiedniego języka

2021-02-04 10:38 UTC, ZytaWisz approved these changes

2021-02-05 21:43 UTC, merged